// <auto-generated />
namespace Visage.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addTicker : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTicker));
        
        string IMigrationMetadata.Id
        {
            get { return "201501270512056_addTicker"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
