// <auto-generated />
namespace Reihs.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class mTags : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mTags));
        
        string IMigrationMetadata.Id
        {
            get { return "201501170211508_mTags"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
