//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visage.Repository {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DescriptionsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DescriptionsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Visage.Repository.DescriptionsResource", typeof(DescriptionsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;post-content&quot;&gt;
        ///	&lt;p class=&quot;lead&quot;&gt;This elegantly formulated exfoliating cleanser gently scrubs away dead skin, improving the appearance of skin tone and texture.&lt;/p&gt;
        ///	&lt;ul class=&quot;factsheet-list&quot;&gt;
        ///		&lt;li&gt; Enhanced skin radiance and luminosity&lt;/li&gt;
        ///		&lt;li&gt; Improved appearance of skin texture, tone and smoothness through mild exfoliation&lt;/li&gt;
        ///	&lt;/ul&gt;
        ///	&lt;ul class=&quot;factsheet-list&quot;&gt;
        ///		&lt;li&gt;Appropriate for: All skin types&lt;/li&gt;
        ///		&lt;li&gt;Purpose: Improve the appearance of skin tone, texture and smoothness.&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AHABHACleanser {
            get {
                return ResourceManager.GetString("AHABHACleanser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;post-content&quot;&gt;
        ///	&lt;p&gt;
        ///		Exfoliates and improves tone and texture revealing brighter skin. A treatment with alpha-hydroxy and beta-hydroxy acids to improve the appearance of skin texture, tone and smoothness by exfoliating skin.
        ///	&lt;/p&gt;
        ///	&lt;ul class=&quot;factsheet-list&quot;&gt;
        ///		&lt;li&gt;Appropriate for: All skin types&lt;/li&gt;
        ///		&lt;li&gt;Purpose: Exfoliate skin to reveal a more youthful appearance&lt;/li&gt;
        ///		&lt;li&gt;Results: Improve the appearance of skin texture, tone and smoothness&lt;/li&gt;
        ///	&lt;/ul&gt;
        ///	&lt;h3 class=&quot;heading&quot;&gt;Use&lt;/h3 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AHABHACream {
            get {
                return ResourceManager.GetString("AHABHACream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;post-content&quot;&gt; &lt;!-- Clarsonic Mia--&gt;
        ///
        ///    &lt;p class=&quot;lead&quot;&gt;
        ///        Cleansing is the essential first step in a healthy skin care ritual. The patented Clarisonic Sonic Cleansing Brush uses a sonic frequency of more than 300 movements per second to deeply cleanse the skin far more effectively, yet more gently, than traditional superficial cleansing or simple rotating brushes. The result is noticeably smoother, more radiant skin. 
        ///    &lt;/p&gt;
        ///    &lt;h3 class=&quot;heading&quot;&gt;Clinical Proof&lt;/h3&gt;
        ///    &lt;ul cl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ClarisonicMia {
            get {
                return ResourceManager.GetString("ClarisonicMia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;post-content&quot;&gt;
        ///	&lt;p class=&quot;lead&quot;&gt;Ultra sheer, broad spectrum UVA/UVB sun protection in a fragrance and oil-free formula.  This oil-free and fragrance-free, ultra sheer physical sunscreen provides broad-spectrum defense against UVA/UVB rays.&lt;/p&gt;
        ///	&lt;ul class=&quot;factsheet-list&quot;&gt;
        ///		&lt;li&gt;Appropriate for: All skin types – gentle enough for sensitive and post-procedure skin&lt;/li&gt;
        ///		&lt;li&gt;Purpose: Broad spectrum UVA/UVB protection&lt;/li&gt;
        ///	&lt;/ul&gt;
        ///	&lt;h3 class=&quot;heading&quot;&gt;Use&lt;/h3&gt;
        ///	&lt;h5&gt;When to apply:&lt;/h5&gt;
        ///	&lt;p&gt;In [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DailyPhysicalDefense {
            get {
                return ResourceManager.GetString("DailyPhysicalDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;post-content&quot;&gt;
        ///	&lt;p class=&quot;lead&quot;&gt;
        ///		Ultra rich moisturizer helps prevent moisture loss and improves skin smoothness to restore your skin’s natural beauty.
        ///		This ultra-rich cream intensely hydrates and replenishes moisture to dry skin with high levels of antioxidants, vitamins C and E.
        ///	&lt;/p&gt;
        ///	&lt;ul class=&quot;factsheet-list&quot;&gt;
        ///		&lt;li&gt;Appropriate for: Normal to dry skin&lt;/li&gt;
        ///		&lt;li&gt;Provides Intense skin hydration and helps replenish moisture&lt;/li&gt;
        ///	&lt;/ul&gt;
        ///	&lt;h3 class=&quot;heading&quot;&gt;Use&lt;/h3&gt;
        ///	&lt;h5&gt;When to  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DermalRepairCream {
            get {
                return ResourceManager.GetString("DermalRepairCream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;post-content&quot;&gt;
        ///	&lt;p class=&quot;lead&quot;&gt; Protect your skin from sun damage with this water resistant (80 minutes), broad spectrum UV protection. This broad spectrum UVA/UVB defense sunscreen protects the skin from the sun’s harmful rays in an oil-free, PABA-free and fragrance-free formulation.&lt;/p&gt;
        ///
        ///	&lt;ul class=&quot;factsheet-list&quot;&gt;
        ///		&lt;li&gt;Appropriate for: All skin types&lt;/li&gt;
        ///		&lt;li&gt;Purpose: water resistant (80 minutes), broad spectrum uva /&gt;UVB protection&gt;&lt;/li&gt;
        ///	&lt;/ul&gt;
        ///	&lt;h3 class=&quot;heading&quot;&gt;Use&lt;/h3&gt;
        ///	&lt;h5 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EnvironmentalDefenseSunscreen50 {
            get {
                return ResourceManager.GetString("EnvironmentalDefenseSunscreen50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;post-content&quot;&gt; &amp;#10;&amp;#9; &lt;p class=&quot;lead&quot;&gt;&amp;#10;&amp;#9;  Introducing a higher standard of beauty with our 3-in-1 skin perfector, Even Up. This patent pending formula instantly evens skin tone and provides SPF 50 protection while its highly effective skin-brightening complex, LUMIRA™, addresses the appearance of skin discoloration.&amp;#10;&amp;#9; &lt;/p&gt;&amp;#10; &lt;/div&gt;.
        /// </summary>
        public static string EvenUp {
            get {
                return ResourceManager.GetString("EvenUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;post-content&quot;&gt;
        ///	&lt;p class=&quot;lead&quot;&gt;
        ///		Our highest customer rated cleanser for all skin types. Removes environmental pollutants, excess oil and makeup, and hydrates and refreshes skin.
        ///		This foaming, soap-free facial cleanser gently purges dirt, makeup, and environmental pollutants from the skin as it hydrates and refreshes.
        ///	&lt;/p&gt;
        ///	&lt;ul class=&quot;factsheet-list&quot;&gt;
        ///		&lt;li&gt;Appropriate for: All skin types&lt;/li&gt;
        ///		&lt;li&gt;Purpose: Skin cleansing and hydration&lt;/li&gt;
        ///	&lt;/ul&gt;
        ///	&lt;h3 class=&quot;heading&quot;&gt;Use&lt;/h3&gt;
        ///	&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FacialCleanser {
            get {
                return ResourceManager.GetString("FacialCleanser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;post-content&quot;&gt;
        ///	&lt;p class=&quot;lead&quot;&gt; Provides hydration and enhances benefits of moisturizer. This unique blend of high and low molecular weight hyaluronic acid effectively replenishes skin’s moisture reservoir.&lt;/p&gt;
        ///	&lt;ul class=&quot;factsheet-list&quot;&gt;
        ///		&lt;li&gt;Appropriate for: All skin types&lt;/li&gt;
        ///		&lt;li&gt;Purpose: Enhances the benefits of daily moisturizer&lt;/li&gt;
        ///		&lt;li&gt;Results: Helps replenish skin’s moisture reservoir&lt;/li&gt;
        ///	&lt;/ul&gt;
        ///	&lt;h3 class=&quot;heading&quot;&gt;Use&lt;/h3&gt;
        ///	&lt;h5&gt;When to apply:&lt;/h5&gt;
        ///	&lt;p&gt;Morning or eveni [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HydratingComplex {
            get {
                return ResourceManager.GetString("HydratingComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul class=&quot;factsheet-list&quot;&gt;
        ///	&lt;li&gt;Unique crème that melts quickly and spreads easily&lt;/li&gt;
        ///	&lt;li&gt;Formulated for night-time use&lt;/li&gt;
        ///	&lt;li&gt;Soothes irritation, redness and flaking sometimes caused by medications such as Retin-A®&lt;/li&gt;
        ///	&lt;li&gt;Safe to use around the eyes&lt;/li&gt;
        ///	&lt;li&gt;Non-comedogenic, sensitivity and fragrance free&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string IntenseMoisturizer {
            get {
                return ResourceManager.GetString("IntenseMoisturizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;post-content&quot;&gt;
        ///	&lt;p class=&quot;lead&quot;&gt;Acne treatment cleanser that helps clear up acne blemishes.  This instant foaming wash with salicylic acid helps remove excess oil and impurities to clear skin and prevent new acne blemishes.&lt;/p&gt;
        ///	&lt;ul class=&quot;factsheet-list&quot;&gt;
        ///		&lt;li&gt;Appropriate for: Acne-prone skin&lt;/li&gt;
        ///		&lt;li&gt;Purpose: Daily facial cleansing and acne treatment&lt;/li&gt;
        ///		&lt;li&gt;&lt;/li&gt;
        ///	&lt;/ul&gt;
        ///	&lt;h3 class=&quot;heading&quot;&gt;Use&lt;/h3&gt;
        ///	&lt;h5&gt;When to apply:&lt;/h5&gt;
        ///	&lt;p&gt;First product used in your morning and evening ski [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PurifyingFoamingWash {
            get {
                return ResourceManager.GetString("PurifyingFoamingWash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;post-content&quot;&gt;
        ///	&lt;p class=&quot;lead&quot;&gt;
        ///		Clinically shown to reduce the appearance of facial redness. A clinical breakthrough that reduces the appearance of visible redness while helping to promote healthy skin.
        ///		Clinical studies show Redness Relief CalmPlex reduces the appearance of acute, UV-induced and chronic visible redness in as early as two weeks, with continued improvement over time.1
        ///		1. Data on file at SkinMedica
        ///	&lt;/p&gt;
        ///	&lt;ul class=&quot;factsheet-list&quot;&gt;
        ///		&lt;li&gt;Appropriate for: All skin typ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RednessReliefCream {
            get {
                return ResourceManager.GetString("RednessReliefCream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;post-content&quot;&gt;
        ///	&lt;p class=&quot;lead&quot;&gt;Helps moisturize and rejuvenate skin. This rich cream with vitamins A, C and E soothes and hydrates stressed, dry skin.&lt;/p&gt;
        ///	&lt;ul class=&quot;factsheet-list&quot;&gt;
        ///		&lt;li&gt;Appropriate for: Normal to dry skin&lt;/li&gt;
        ///		&lt;li&gt;Provides Nourishes and hydrates dry skin&lt;/li&gt;
        ///	&lt;/ul&gt;
        ///	&lt;h3 class=&quot;heading&quot;&gt;Use&lt;/h3&gt;
        ///	&lt;h5&gt;When to apply:&lt;/h5&gt;
        ///	&lt;p&gt;Twice daily after cleansing, toning and applying treatment products&lt;/p&gt;
        ///	&lt;h5&gt;Where to apply:&lt;/h5&gt;
        ///	&lt;p&gt;Face (neck and chest if desired)&lt;/p&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RejuvenateMoisturizer {
            get {
                return ResourceManager.GetString("RejuvenateMoisturizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;post-content&quot;&gt;
        ///
        ///	&lt;p class=&quot;lead&quot;&gt;Removes dirt and impurities. This refreshing, non-drying toner gently exfoliates dead skin cells and refines pores with mildly exfoliating alpha-hydroxy acids.&lt;/p&gt;
        ///
        ///	&lt;ul class=&quot;factsheet-list&quot;&gt;
        ///		&lt;li&gt;Appropriate for: Normal to dry skin&lt;/li&gt;
        ///		&lt;li&gt;Purpose: Gently refines skin and restores PH balance&lt;/li&gt;
        ///		&lt;li&gt;&lt;/li&gt;
        ///	&lt;/ul&gt;
        ///	&lt;h3 class=&quot;heading&quot;&gt;Use&lt;/h3&gt;
        ///	&lt;h5&gt;When to apply:&lt;/h5&gt;
        ///	&lt;p&gt;Apply following cleansing&lt;/p&gt;
        ///	&lt;h5&gt;Where to apply:&lt;/h5&gt;
        ///	&lt;p&gt;Face and ne [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RejuvenateToner {
            get {
                return ResourceManager.GetString("RejuvenateToner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;post-content&quot;&gt;
        ///	&lt;p class=&quot;lead&quot;&gt;Renews skin and diminishes the appearance of fine lines.&lt;/p&gt;
        ///
        ///	&lt;ul class=&quot;factsheet-list&quot;&gt;
        ///		&lt;li&gt;Appropriate for: All skin types pre-conditioned by using Retinol Complex 0.25% or another retinoid product&lt;/li&gt;
        ///		&lt;li&gt;Purpose: Enhance skin tone, texture, and resiliency&lt;/li&gt;
        ///		&lt;li&gt;
        ///			Results:
        ///			&lt;ul&gt;
        ///				&lt;li&gt; Diminished appearance of fine lines and coarse wrinkles&lt;/li&gt;
        ///				&lt;li&gt; Enhanced skin tone and texture&lt;/li&gt;
        ///			&lt;/ul&gt;
        ///		&lt;/li&gt;
        ///	&lt;/ul&gt;
        ///	&lt;h3 class=&quot;head [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RetinolComplex05 {
            get {
                return ResourceManager.GetString("RetinolComplex05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;post-content&quot;&gt;
        ///	&lt;p class=&quot;lead&quot;&gt;Renews skin and diminishes the appearance of fine lines.&lt;/p&gt;
        ///	&lt;ul class=&quot;factsheet-list&quot;&gt;
        ///		&lt;li&gt;Appropriate for: All skin types pre-conditioned by using Retinol Complex 0.25% or another retinoid product&lt;/li&gt;
        ///		&lt;li&gt;Purpose: Enhance skin tone, texture, and resiliency&lt;/li&gt;
        ///		&lt;li&gt;
        ///			Results:
        ///			&lt;ul&gt;
        ///				&lt;li&gt;  Diminished appearance of fine lines and coarse wrinkles&lt;/li&gt;
        ///				&lt;li&gt; Enhanced skin tone and texture&lt;/li&gt;
        ///			&lt;/ul&gt;
        ///		&lt;/li&gt;
        ///	&lt;/ul&gt;
        ///	&lt;h3 class=&quot;headi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RetinolComplex1 {
            get {
                return ResourceManager.GetString("RetinolComplex1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;post-content&quot;&gt;
        ///	&lt;p class=&quot;lead&quot;&gt;Renews skin and diminishes the appearance of fine lines.&lt;/p&gt;
        ///	&lt;ul class=&quot;factsheet-list&quot;&gt;
        ///		&lt;li&gt;Appropriate for: All skin types&lt;/li&gt;
        ///		&lt;li&gt;Purpose: Enhance skin tone, texture, and resiliency&lt;/li&gt;
        ///		&lt;li&gt;
        ///			Results:
        ///			&lt;ul&gt;
        ///				&lt;li&gt;  Diminished appearance of fine lines and coarse wrinkles&lt;/li&gt;
        ///				&lt;li&gt; Enhanced skin tone and texture&lt;/li&gt;
        ///			&lt;/ul&gt;
        ///		&lt;/li&gt;
        ///	&lt;/ul&gt;
        ///	&lt;h3 class=&quot;heading&quot;&gt;Use&lt;/h3&gt;
        ///	&lt;h5&gt;When to apply:&lt;/h5&gt;
        ///	&lt;p&gt;In the evening after cleansing  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RetinolComplex25 {
            get {
                return ResourceManager.GetString("RetinolComplex25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;post-content&quot;&gt; &amp;#10;&amp;#9; &lt;p class=&quot;lead&quot;&gt;&amp;#10;&amp;#9;  This eyebrow conditioner enhances the look of luxurious eyebrows for dramatic, natural beauty. RevitaBrow® Advanced delivers a proprietary blend of scientifically-advanced peptides, revitalizing extracts and nutritive vitamins to help beautify and enhance the look of bold, defined brows.&amp;#10;&amp;#9; &lt;/p&gt;&amp;#10; &lt;/div&gt;.
        /// </summary>
        public static string RevitaBrow {
            get {
                return ResourceManager.GetString("RevitaBrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;post-content&quot;&gt;
        ///
        ///	&lt;p class=&quot;lead&quot;&gt;
        ///		RevitaLash is a unique eyelash conditioner that will help you achieve the beautiful look of longer, thicker, and fuller eyelashes.
        ///		Like liquid eyeliner, RevitaLash is simply applied once a day. Within three to ten weeks, your own natural eyelashes will look longer, thicker, fuller, and BEAUTIFUL!
        ///	&lt;/p&gt;
        ///&lt;/div&gt;.
        /// </summary>
        public static string Revitalash1 {
            get {
                return ResourceManager.GetString("Revitalash1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;post-content&quot;&gt;
        ///	&lt;p class=&quot;lead&quot;&gt;
        ///		Helps minimize the appearance of scars.
        ///		Supports key aspects of scar formation to aid in healing. Clinically tested to provide earlier and greater overall improvements in the appearance of scars.
        ///	&lt;/p&gt;
        ///	&lt;ul class=&quot;factsheet-list&quot;&gt;
        ///		&lt;li&gt;Appropriate for: All skin types&lt;/li&gt;
        ///		&lt;li&gt;Purpose: Diminish the appearance of red or pink scars&lt;/li&gt;
        ///		&lt;li&gt;Results: Softens and minimizes the appearance of scars that are red or pink&lt;/li&gt;
        ///	&lt;/ul&gt;
        ///	&lt;h3 class=&quot;heading&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ScarRecoveryGelwithC2oz {
            get {
                return ResourceManager.GetString("ScarRecoveryGelwithC2oz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;post-content&quot;&gt;
        ///	&lt;p class=&quot;lead&quot;&gt;Helps minimize the appearance of scars.&lt;/p&gt;
        ///	&lt;ul class=&quot;factsheet-list&quot;&gt;
        ///		&lt;li&gt;Appropriate for: All skin types&lt;/li&gt;
        ///		&lt;li&gt;Purpose: Diminish the appearance of red or pink scars&lt;/li&gt;
        ///		&lt;li&gt;Results: Softens and minimizes the appearance of scars that are red or pink&lt;/li&gt;
        ///	&lt;/ul&gt;
        ///	&lt;h3 class=&quot;heading&quot;&gt;Use&lt;/h3&gt;
        ///	&lt;h5&gt;When to apply:&lt;/h5&gt;
        ///	&lt;p&gt;Morning and evening after the wound has healed. Use should continue until the scar appears flat and white without redness.&lt;/p [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ScarRecoveryGelwithC5oz {
            get {
                return ResourceManager.GetString("ScarRecoveryGelwithC5oz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;post-content&quot;&gt;
        ///	&lt;p class=&quot;lead&quot;&gt;
        ///		Gently removes environmental pollutants and cleanses while providing hydration for sensitive, post-procedure skin.
        ///		Gently cleanses the most sensitive, post-procedure skin with a combination of soothing botanical extracts.
        ///	&lt;/p&gt;
        ///	&lt;ul class=&quot;factsheet-list&quot;&gt;
        ///		&lt;li&gt;Appropriate for: Dry, sensitive and post-procedure skin&lt;/li&gt;
        ///		&lt;li&gt;Purpose: Skin cleansing and hydration&lt;/li&gt;
        ///		&lt;li&gt;&lt;/li&gt;
        ///	&lt;/ul&gt;
        ///	&lt;h3 class=&quot;heading&quot;&gt;Use&lt;/h3&gt;
        ///	&lt;h5&gt;When to apply:&lt;/h5&gt;
        ///	&lt;p&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SensitiveSkinCleanser {
            get {
                return ResourceManager.GetString("SensitiveSkinCleanser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;post-content&quot;&gt;
        ///	&lt;p class=&quot;lead&quot;&gt;
        ///		Brightens dull skin and minimizes the appearance of skin discoloration and dark spots. Improvements seen as early as 4 weeks.
        ///		The Next Generation in Skin Brightening Lytera is a brightening product that addresses the appearance of skin discoloration:
        ///	&lt;/p&gt;
        ///	&lt;article&gt;
        ///		&lt;h3 class=&quot;heading&quot;&gt;Benefits&lt;/h3&gt;
        ///		&lt;ul class=&quot;factsheet-list&quot;&gt;
        ///			&lt;li&gt;Effectively reduces the appearance of dark spots creating a more even skin tone&lt;/li&gt;
        ///			&lt;li&gt;Results seen in as ea [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SkinBrightening {
            get {
                return ResourceManager.GetString("SkinBrightening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;post-content&quot;&gt; &amp;#10;&amp;#9; &lt;p class=&quot;lead&quot;&gt;&amp;#10;&amp;#9;  This water resistant, broad spectrum sunscreen makes protecting your skin easy, 365 days a year. Perfectly portable and easy to reapply, it offers powerful SPF 50 UVA/UVB protection with sheer, natural-looking coverage.&amp;#10;&amp;#9; &lt;/p&gt;&amp;#10;&amp;#9; &lt;ul class=&quot;factsheet-list&quot;&gt;&amp;#10;&amp;#9;  &lt;li&gt;Net Wt. 6 g / 0.21 oz.&lt;/li&gt;&amp;#10;&amp;#9;  &lt;li&gt;90 day supply based on typical use&lt;/li&gt;&amp;#10;&amp;#9; &lt;/ul&gt;&amp;#10; &lt;/div&gt;.
        /// </summary>
        public static string Sunforgettable {
            get {
                return ResourceManager.GetString("Sunforgettable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;post-content&quot;&gt;
        ///	&lt;p class=&quot;lead&quot;&gt;
        ///		Hydrates and helps restore your skin’s moisture barrier and balance.
        ///		This ceramide-rich treatment cream with the patented growth factor blend TNS® and
        ///		peptides goes beyond an ordinary moisturizer to rapidly restore skin’s moisture balance while soothing and hydrating the driest post-procedure and compromised skin.
        ///	&lt;/p&gt;
        ///	&lt;ul class=&quot;factsheet-list&quot;&gt;
        ///		&lt;li&gt;Appropriate for: Dry or post-procedure skin. &lt;/li&gt;
        ///		&lt;li&gt;Provides: Hydration, helps restore skin [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TNSCeramideTreatmentCream {
            get {
                return ResourceManager.GetString("TNSCeramideTreatmentCream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;post-content&quot;&gt;
        ///
        ///	&lt;p class=&quot;lead&quot;&gt;
        ///		All-in-one skin rejuvenating treatment improves the appearance of fine lines, wrinkles, skin tone and texture.
        ///		Our unparalleled patented treatment is the first and only rejuvenating serum to combine the benefits of the proprietary growth factor blend,
        ///		TNS Recovery Complex®, with potent antioxidants, peptides and other innovative ingredients to restore a youthful look to skin.
        ///	&lt;/p&gt;
        ///	&lt;ul class=&quot;factsheet-list&quot;&gt;
        ///		&lt;li&gt;Appropriate for: All skin types&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TNSEssentialSerum {
            get {
                return ResourceManager.GetString("TNSEssentialSerum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;post-content&quot;&gt;
        ///	&lt;p class=&quot;lead&quot;&gt;
        ///		Reduces the appearance of fine lines, wrinkles and puffiness around the eyes.
        ///		This luxurious eye treatment cream formulated with the patented growth factor blend TNS®, peptides,
        ///		high concentrations of antioxidant vitamins C and E and hyaluronic acid helps to increase firmness, improve the appearance of fine lines and wrinkles and minimize dark circles.
        ///	&lt;/p&gt;
        ///	&lt;ul class=&quot;factsheet-list&quot;&gt;
        ///		&lt;li&gt;Appropriate for: Normal to dry skin&lt;/li&gt;
        ///		&lt;li&gt;Purpose: I [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TNSEyeRepair {
            get {
                return ResourceManager.GetString("TNSEyeRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;post-content&quot;&gt;
        ///	&lt;p class=&quot;lead&quot;&gt;
        ///		Reduces the appearance of fine lines, wrinkles and dark circles around the eyes and improves skin tone and texture.
        ///		This lightweight eye cream with the patented growth factor blend TNS®, peptides and chrysin helps brighten the skin around the eyes and minimize the appearance of fine lines, wrinkles and dark circles.
        ///	&lt;/p&gt;
        ///	&lt;ul class=&quot;factsheet-list&quot;&gt;
        ///		&lt;li&gt;Appropriate for: Normal or combination skin&lt;/li&gt;
        ///		&lt;li&gt;Purpose: Enhance tone and texture of skin  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TNSIlluminatingEyeCream {
            get {
                return ResourceManager.GetString("TNSIlluminatingEyeCream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;post-content&quot;&gt;
        ///
        ///	&lt;p class=&quot;lead&quot;&gt;Simple, 2-product system enhances natural lip color and volume.&lt;/p&gt;
        ///	&lt;p&gt;
        ///		TNS Lip Renewal -
        ///		This treatment cream combines the rejuvenating strength of the patented growth factor blend TNS® and collagen-filling spheres to enhance the fullness of the lips and smooth surface imperfections.
        ///	&lt;/p&gt;
        ///	&lt;p&gt;
        ///		Lip Plumper -
        ///		This clear plumping gloss with niacin enhances the natural color of lips.
        ///	&lt;/p&gt;
        ///	&lt;ul class=&quot;factsheet-list&quot;&gt;
        ///		&lt;li&gt;Appropriate for: All [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TNSPlumpLipSystem {
            get {
                return ResourceManager.GetString("TNSPlumpLipSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;post-content&quot;&gt;
        ///	&lt;p class=&quot;lead&quot;&gt;
        ///		Clinically shown to reduce the appearance of skin discoloration and improve the appearance of fine lines and wrinkles.
        ///		This unparalleled patented treatment gel, using the highest level of a combination of growth factors, will enhance skin tone and help minimize the appearance of fine lines and wrinkles.
        ///	&lt;/p&gt;
        ///	&lt;ul class=&quot;factsheet-list&quot;&gt;
        ///		&lt;li&gt;Appropriate for: All skin types&lt;/li&gt;
        ///		&lt;li&gt;Purpose: Rejuvenate skin&lt;/li&gt;
        ///		&lt;li&gt;
        ///			Results:
        ///			&lt;ul&gt;
        ///				&lt;l [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TNSRecovery {
            get {
                return ResourceManager.GetString("TNSRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;post-content&quot;&gt;
        ///	&lt;p class=&quot;lead&quot;&gt;
        ///		Lightweight noncomedogenic moisturizer.
        ///		This light, oil-free formula effectively hydrates skin while antioxidant vitamins C and E protect against free radical damage.
        ///	&lt;/p&gt;
        ///	&lt;ul class=&quot;factsheet-list&quot;&gt;
        ///		&lt;li&gt;Appropriate for: Normal to oily skin&lt;/li&gt;
        ///		&lt;li&gt;Provides Facial hydration and improves the overall appearance of skin condition&lt;/li&gt;
        ///	&lt;/ul&gt;
        ///	&lt;h3 class=&quot;heading&quot;&gt;Use&lt;/h3&gt;
        ///	&lt;h5&gt;When to apply:&lt;/h5&gt;
        ///	&lt;p&gt;Twice daily after cleansing, toning and apply [rest of string was truncated]&quot;;.
        /// </summary>
        public static string UltraSheer {
            get {
                return ResourceManager.GetString("UltraSheer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;post-content&quot;&gt;
        ///	&lt;p class=&quot;lead&quot;&gt;
        ///		Smoothes the appearance of skin around the eyes and reduces the appearance of puffiness and fine wrinkles.
        ///		This oil-free serum soothes the delicate skin around the eyes to rapidly reduce the appearance of puffiness and fine lines.
        ///	&lt;/p&gt;
        ///	&lt;ul class=&quot;factsheet-list&quot;&gt;
        ///		&lt;li&gt;Appropriate for: All skin types&lt;/li&gt;
        ///		&lt;li&gt;Purpose: Enhances skin texture around the eyes&lt;/li&gt;
        ///		&lt;li&gt;Results: Smoother looking skin around the eyes. Reduced appearance of puffiness&lt;/l [rest of string was truncated]&quot;;.
        /// </summary>
        public static string UpliftingEyeSerum {
            get {
                return ResourceManager.GetString("UpliftingEyeSerum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul class=&quot;factsheet-list&quot;&gt;
        ///	&lt;li&gt;SPF 46 with 9% Micronized Zinc Oxide and high-purity Niacinamide (vitamin B3)&lt;/li&gt;
        ///	&lt;li&gt;Calms and protects sensitive, acne-prone skin&lt;/li&gt;
        ///	&lt;li&gt;Very lightweight, oil-free formula leaves no residue on skin’s surface&lt;/li&gt;
        ///	&lt;li&gt;Use alone or under makeup every day&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string UVClear46 {
            get {
                return ResourceManager.GetString("UVClear46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul class=&quot;factsheet-list&quot;&gt;
        ///	&lt;li&gt;SPF 40 with 9% Zinc Oxide&lt;/li&gt;
        ///	&lt;li&gt;Light, sheer daily facial moisturizer with UV protection for the face, either alone or under makeup&lt;/li&gt;
        ///	&lt;li&gt;Glides on easily and absorbs quickly into the skin&lt;/li&gt;
        ///	&lt;li&gt;Hyaluronic acid to increase skin smoothness, softness and decrease wrinkles&lt;/li&gt;
        ///	&lt;li&gt;Paraben-Free&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string UVDaily40 {
            get {
                return ResourceManager.GetString("UVDaily40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul class=&quot;factsheet-list&quot;&gt;
        ///	&lt;li&gt;SPF 41 with 9% Zinc Oxide &amp;amp; 7% Titanium Dioxide&lt;/li&gt;
        ///	&lt;li&gt;Chemical Free-natural mineral UV protection&lt;/li&gt;
        ///	&lt;li&gt;Oil-free, Paraben-free and fragrance free&lt;/li&gt;
        ///	&lt;li&gt;Water Resistant&lt;/li&gt;
        ///	&lt;li&gt;Ideal for very sensitive skin and children&lt;/li&gt;
        ///	&lt;li&gt;Absorbs quickly and can be used on the face and body&lt;/li&gt;
        ///	&lt;li&gt;Antioxidants to neutralize free radicals to help prevent sun damage&lt;/li&gt;
        ///	&lt;li&gt;Lightly tinted&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string UVPhysical41 {
            get {
                return ResourceManager.GetString("UVPhysical41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul class=&quot;factsheet-list&quot;&gt;
        ///	&lt;li&gt;SPF 45 with 9% Zinc Oxide&lt;/li&gt;
        ///	&lt;li&gt;Great for all skin types, especially oily or acne-prone skin&lt;/li&gt;
        ///	&lt;li&gt;Specifically formulated to provide oil-free protection for the face, either alone or under makeup&lt;/li&gt;
        ///	&lt;li&gt;Light sheer formula that spreads quickly and leaves no residue on skin’s surface&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string UVShield45 {
            get {
                return ResourceManager.GetString("UVShield45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;post-content&quot;&gt;
        ///	&lt;p class=&quot;lead&quot;&gt;
        ///		Improves the appearance of skin tone and texture with vitamins C &amp;amp; E.
        ///		This silky, fragrance-free formula with stabilized vitamins C and E provides extraordinary antioxidant protection, helping to improve the appearance of skin tone, texture and firmness.
        ///	&lt;/p&gt;
        ///	&lt;ul class=&quot;factsheet-list&quot;&gt;
        ///		&lt;li&gt;Appropriate for: All skin types&lt;/li&gt;
        ///		&lt;li&gt;Purpose: Improve the appearance of skin tone and texture&lt;/li&gt;
        ///		&lt;li&gt;Results: Enhanced skin brightness for a more [rest of string was truncated]&quot;;.
        /// </summary>
        public static string VitaminCE {
            get {
                return ResourceManager.GetString("VitaminCE", resourceCulture);
            }
        }
    }
}
